# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-17 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('head', models.CharField(max_length=255, unique=True)),
                ('amount', models.FloatField()),
                ('method', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='TransactionHead',
        ),
    ]
