# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-19 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import enumerify.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171217_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Active'), (2, b'Inactive'), (3, b'Draft')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('head', models.CharField(max_length=255, unique=True)),
                ('amount', models.FloatField()),
                ('method', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
